language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mfvxVeY+rubJzCVHWObOKRoVq4TzJvhpCI52FhlfFiHS5ATsaojesM5yhSOZMToO4XY6Wz+KvZ8PSRA25OTATSudhIMmPLTsX2R5+u7QamiGZnbCj5fcysktgfKBaG52a9UH2FcFbCZUJlGyWDYuN5uP5BdN4MU/8VLK9TsccFKPfosVQMlL72L/CaTgoRj1CER+paSe1HBTZ7QMQSp82KcHveR/kLVSQA2+w8eokVfotli1CayRbr1D2bYN5jNuSy8RFkVFbbJvVcyLdTPW7DNmIy0RgaohvfCmwjmoBzn4oPz1+jXSPij4Xxy/MKe1AJdfvf4PMmh3DG+wdKEWbmvqtIVvUtA9PMz9tnHA1AhEnZd42e8usCkIjZnX/duJYwWguDQEII8/KIv6Nu5HhhfKMCO+a6os6tshSOXNreRWcPYZnT0wMUzFMpSO/n8xcLTbItWCj+5xNdVrBt/t/KHCZfrsJ7TR5jDkp9ZJip03PsmLJswRImO4yaEFd/oP6tbFRJ7uxwJYzr5ELCE69Az2Ydh3YLCN8fatQEv0D3udOLfKdCFQ2e1q3Ah2TZBHonK6li17MGOVUG6ajIZOPXfkfhpTeU06K31De6vpOUAAEOe61THWjI3d764zJoL/onuHnb6VMxi0iPvLBiNJOK3cpAmntk40gcLv0X/yO2U=
  app: mighty-waters-43172
  on:
    repo: ryandthorn/node-shopping-list-integration-tests
