language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: efYsAfZ96AKZ3y7QqOdmpZ/TReVStAs61+mcId+e3Ux3o64FtqsA2AqCmxVA9JsvDeGqyUTPXvMf0YxK08gsJw9SekmvAhU45KMyhLMRDsGz2yHvldQD7fRXGDusKQ72W7imyEmulXx9ztA/mp9NZoQfQmaIK9JHam05qZoL9UOfeSFgCPu9nsV+YeUMbXXfS/D4glssnalVr4alsBJrdwTHSnxaYJFQxEuzYvh7ytBlftbEiFYuA4WL/F93qfbm6p7E6/3f1K6Us9dyaNwtYkp2EZ5OQ9k9js/90EwOwITxeFlJ3QhJk96q6L2d3728lmG+ITs5MUlmAbjFXJQyj8lz9XzUrtI0zVDhRplBvxPPK5hsh/nDMwNY2zdBZMTyJm8VR2RnSbXJXqy6sRIkvA6mpUUb3PYCAMzHHhxbc6GT2NQOWHNPuqAd8Rx1jRpVejw7e7ZMPy/M8IXck0dOqLeCCsXo90LXe6fXbytv4Lcz6cSYZ96dccMPir9wOgzi8aw1dj/GPC6bQcHrmdOjf6alBUhHwNtPIL+4TwqLQK9H3yvlRPPeJhKRQ1VUpx1UKGQzKx4ZIcMBZYC5/gJGLqUFO/9g6rYSTWVdKBc5kBo/qUoJ3g5ZfOgOuRie98rleeOTE2Z2EBOp+ui+86PYuH6cGpHofgcM4dnXIbx6d5Q=
  app: secret-temple-55017
  on:
    repo: ryandthorn/node-shopping-list-integration-tests
